# Generated by Django 2.2.6 on 2021-05-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20210514_1057'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique fields',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_pair'),
        ),
    ]
